# Generated by Django 2.2.5 on 2019-12-03 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='type_article',
        ),
        migrations.CreateModel(
            name='InscriptionExposant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine_exposant', models.CharField(choices=[('0', 'accueil'), ('1', 'bar'), ('2', 'internet'), ('3', 'logistique'), ('4', 'concert'), ('5', 'Sécurité'), ('6', "N'importe...")], default='0', max_length=10, verbose_name='domaine')),
                ('description', models.TextField(verbose_name='Donnez nous quelques informations a propos du stand que vous voulez tenir')),
                ('date_inscription', models.DateTimeField(editable=False, verbose_name="Date d'inscritpion")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionBenevole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine_benevole', models.CharField(choices=[('0', 'accueil'), ('1', 'bar'), ('2', 'internet'), ('3', 'logistique'), ('4', 'concert'), ('5', 'Sécurité'), ('6', "N'importe...")], default='0', max_length=10, verbose_name='domaine')),
                ('description', models.TextField(verbose_name='Vous pouvez expliciter ici ce que vous préféreriez faire')),
                ('date_inscription', models.DateTimeField(editable=False, verbose_name="Date d'inscritpion")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
