# Generated by Django 2.2.5 on 2019-12-03 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_auto_20191203_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='a_signe',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='accepter_annuaire',
        ),
    ]
