# Generated by Django 2.2.5 on 2019-12-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0003_auto_20191203_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='nom',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='profil',
            name='prenom',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='domaine_benevole',
            field=models.CharField(choices=[('0', 'Accueil'), ('1', 'Bar'), ('2', 'Internet'), ('3', 'Logistique'), ('4', 'Concert'), ('5', 'Sécurité'), ('6', "N'importe...")], default='0', max_length=10, verbose_name='Domaine préférentiel du bénévolat'),
        ),
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='domaine_exposant',
            field=models.CharField(choices=[('0', 'Association'), ('1', 'Particulier'), ('2', 'Institution'), ('3', 'Commerçant'), ('4', 'Nourriture sur place'), ('5', 'Conférence'), ('6', 'Atelier'), ('7', 'autre')], default='0', max_length=10, verbose_name='Type du stand'),
        ),
    ]
