# Generated by Django 2.2.5 on 2019-12-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0004_auto_20191204_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='prenom',
        ),
        migrations.AddField(
            model_name='profil',
            name='code_postal',
            field=models.CharField(blank=True, default='66000', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='commune',
            field=models.CharField(blank=True, default='Perpignan', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscritpion"),
        ),
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscritpion"),
        ),
        migrations.DeleteModel(
            name='Adresse',
        ),
    ]
