# Generated by Django 2.2.8 on 2020-01-14 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permaculturelne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionbenevole',
            name='dispo_avantfestival',
            field=models.TextField(blank=True, verbose_name='Quelle est votre disponibilité pour venir aider à la mise en place du festival (les jours précédant le festival) ?'),
        ),
        migrations.AddField(
            model_name='inscriptionbenevole',
            name='heures_festival',
            field=models.CharField(choices=[(0, '2h dans la journée'), (3, 'Le matin'), (4, "L'après midi"), (5, 'Toute la journée')], default='0', max_length=10, verbose_name="Combien d'heures"),
        ),
        migrations.AddField(
            model_name='inscriptionbenevole',
            name='jours_festival',
            field=models.CharField(choices=[(0, 'Samedi'), (1, 'Dimanche'), (2, 'Samedi et dimanche')], default='0', max_length=10, verbose_name='Quel(s) jour(s) du festival seriez-vous disponible'),
        ),
        migrations.AddField(
            model_name='inscriptionexposant',
            name='is_tombola',
            field=models.BooleanField(default=False, verbose_name='Je souhaite offrir un lot pour la tombola'),
        ),
        migrations.AddField(
            model_name='inscriptionexposant',
            name='lot_tombola',
            field=models.TextField(blank=True, null=True, verbose_name='Quel lot proposez vous pour la tombola?'),
        ),
        migrations.AddField(
            model_name='inscriptionexposant',
            name='nom_structure',
            field=models.TextField(blank=True, verbose_name='Nom de la structure, association, autre'),
        ),
        migrations.AddField(
            model_name='inscriptionexposant',
            name='nombre_tables',
            field=models.CharField(choices=[(0, 'pas de table'), (1, '1 table'), (2, '2 tables')], default='0', max_length=10, verbose_name='Combien de tables voulez vous réserver ?'),
        ),
        migrations.AddField(
            model_name='inscriptionexposant',
            name='plaque',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro de la plaque minéralogique doit etre au format AA123BB', regex='^[A-Za-z]{2}[0-9]{3}[A-Za-z]{2}$')], verbose_name='Numéro de la plaque minéralogique du véhicule utilisé pour le transport du matériel'),
        ),
        migrations.AddField(
            model_name='inscriptionexposant',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 10 chiffres', regex='^\\d{9,10}$')], verbose_name='Numéro de téléphone de la personne joignable pendant le festival'),
        ),
        migrations.AddField(
            model_name='inscriptionexposant',
            name='type_exposant',
            field=models.CharField(choices=[('0', 'Association'), ('1', 'Particulier'), ('2', 'Institution'), ('3', 'Commerçant'), ('4', 'Nourriture sur place'), ('5', 'Conférence'), ('6', 'Atelier'), ('7', 'autre')], default='0', max_length=10, verbose_name='Type de la structure'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='description',
            field=models.TextField(blank=True, verbose_name='Vous pouvez expliciter ici ce que vous préférez faire, vos disponibilités, etc'),
        ),
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscrition"),
        ),
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='description',
            field=models.TextField(blank=True, verbose_name='Vous pouvez préciser le stand que vous voulez tenir'),
        ),
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='domaine_exposant',
            field=models.CharField(choices=[('0', 'Agriculture'), ('1', 'Alimentaire'), ('2', 'Artisanat'), ('3', 'Bien être'), ('4', 'Habitat'), ('5', 'Informations'), ('6', 'Jeux'), ('7', 'autre')], default='0', max_length=10, verbose_name='Domaine principal'),
        ),
    ]
