# Generated by Django 2.2.8 on 2020-01-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permaculturelne', '0003_auto_20200114_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='statut_adhesion',
            field=models.IntegerField(choices=[('', '-----------'), (0, "Je ne suis pas (ou plus) membre de l'asso 'Ramene Ta Graine'"), (1, "Je suis déjà adhérent de l'asso 'Ramene Ta graine', ma cotisation est à jour"), (2, "Je suis déjà adhérent et 'membre équipe' de l'asso 'Ramene Ta graine'")], default='0'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jours_festival',
            field=models.CharField(choices=[('0', '----------'), ('1', 'Samedi'), ('2', 'Dimanche'), ('3', 'Samedi et dimanche'), ('4', 'Pas de bénévolat pendant le festival (mais avant ou après)')], default='0', max_length=10, verbose_name='Quel(s) jour(s) du festival seriez-vous disponible'),
        ),
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description (brève) du stand que vous voulez tenir'),
        ),
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='lot_tombola',
            field=models.TextField(blank=True, null=True, verbose_name='Quel(s) lot(s) proposez vous pour la tombola?'),
        ),
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='nombre_tables',
            field=models.CharField(choices=[(0, '----------'), ('1', 'pas de table'), ('2', '1 table'), ('3', '2 tables')], default='0', max_length=10, verbose_name='Combien de tables voulez vous réserver ?'),
        ),
    ]
