# Generated by Django 2.2.8 on 2020-01-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permaculturelne', '0004_auto_20200114_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='description',
            field=models.TextField(blank=True, verbose_name='Remarques, suggestions, infos complémentaires :'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='heures_festival',
            field=models.CharField(choices=[('0', '----------'), ('1', '2h dans la journée'), ('2', 'Le matin'), ('3', "L'après midi"), ('4', 'Toute la journée')], default='0', max_length=10, verbose_name="Combien d'heures ?"),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jours_festival',
            field=models.CharField(choices=[('0', '----------'), ('1', 'Samedi'), ('2', 'Dimanche'), ('3', 'Samedi et dimanche'), ('4', 'Dans la semaine avant pour préparer'), ('5', 'Dans la semaine après pour ranger')], default='0', max_length=10, verbose_name='Quel(s) jour(s) du festival seriez-vous disponible ?'),
        ),
    ]
