# Generated by Django 2.2.9 on 2020-01-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permaculturelne', '0006_inscriptionexposant_jours_festival'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionbenevole',
            name='statut_benevole',
            field=models.CharField(choices=[('0', 'Inscription déposée'), ('1', 'Inscription en cours de validation'), ('2', 'Inscription validée'), ('3', 'Inscription refusée'), ('4', 'Inscription annulée')], default='0', max_length=10, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='inscriptionexposant',
            name='statut_exposant',
            field=models.CharField(choices=[('0', 'Inscription déposée'), ('1', 'Inscription incomplète ou en cours de validation'), ('2', 'Inscription validée'), ('3', 'Inscription refusée'), ('4', 'Inscription annulée')], default='0', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='lot_tombola',
            field=models.TextField(blank=True, null=True, verbose_name='Si oui, quel(s) lot(s) proposez vous pour la tombola?'),
        ),
    ]
