# Generated by Django 2.2.9 on 2020-02-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permaculturelne', '0008_profil_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscriptionbenevole',
            name='heures_festival',
        ),
        migrations.RemoveField(
            model_name='inscriptionbenevole',
            name='jours_festival',
        ),
        migrations.AddField(
            model_name='inscriptionbenevole',
            name='jour_dim',
            field=models.BooleanField(default=False, verbose_name='Dimanche'),
        ),
        migrations.AddField(
            model_name='inscriptionbenevole',
            name='jour_jeu',
            field=models.BooleanField(default=False, verbose_name='Jeudi'),
        ),
        migrations.AddField(
            model_name='inscriptionbenevole',
            name='jour_lun',
            field=models.BooleanField(default=False, verbose_name='Lundi'),
        ),
        migrations.AddField(
            model_name='inscriptionbenevole',
            name='jour_mer',
            field=models.BooleanField(default=False, verbose_name='Mercredi'),
        ),
        migrations.AddField(
            model_name='inscriptionbenevole',
            name='jour_sam',
            field=models.BooleanField(default=False, verbose_name='Samedi'),
        ),
        migrations.AddField(
            model_name='inscriptionbenevole',
            name='jour_ven',
            field=models.BooleanField(default=False, verbose_name='Vendredi'),
        ),
    ]
