# Generated by Django 2.2.9 on 2020-02-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permaculturelne', '0009_auto_20200207_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionbenevole',
            name='is_equipe',
            field=models.BooleanField(default=False, verbose_name='Membre equipe'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jour_dim',
            field=models.BooleanField(default=False, verbose_name='Dispo le Dimanche'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jour_jeu',
            field=models.BooleanField(default=False, verbose_name='Dispo le Jeudi'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jour_lun',
            field=models.BooleanField(default=False, verbose_name='Dispo le Lundi'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jour_mer',
            field=models.BooleanField(default=False, verbose_name='Dispo le Mercredi'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jour_sam',
            field=models.BooleanField(default=False, verbose_name='Dispo le Samedi'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jour_ven',
            field=models.BooleanField(default=False, verbose_name='Dispo le Vendredi'),
        ),
    ]
