# Generated by Django 2.2.9 on 2020-02-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permaculturelne', '0010_auto_20200207_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscriptionbenevole',
            name='is_equipe',
        ),
        migrations.AddField(
            model_name='profil',
            name='is_equipe',
            field=models.BooleanField(default=False, verbose_name='Membre equipe'),
        ),
    ]
