# Generated by Django 2.2.9 on 2020-02-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permaculturelne', '0011_auto_20200207_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jour_dim',
            field=models.BooleanField(default=False, verbose_name='Disponible le Dimanche 31 mai'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jour_jeu',
            field=models.BooleanField(default=False, verbose_name='Disponible le Jeudi 28 mai'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jour_lun',
            field=models.BooleanField(default=False, verbose_name='Disponible le Lundi 01 juin'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jour_mer',
            field=models.BooleanField(default=False, verbose_name='Disponible le Mercredi 27 mai'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jour_sam',
            field=models.BooleanField(default=False, verbose_name='Disponible le Samedi 30 mai'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jour_ven',
            field=models.BooleanField(default=False, verbose_name='Disponible le Vendredi 29 mai'),
        ),
    ]
