# Generated by Django 2.2.9 on 2020-02-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permaculturelne', '0012_auto_20200207_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='plaque',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numéro de la plaque minéralogique du véhicule utilisé pour le transport du matériel'),
        ),
    ]
