# Generated by Django 2.2.9 on 2020-02-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permaculturelne', '0013_auto_20200212_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='type_exposant',
            field=models.CharField(choices=[('0', 'Association'), ('1', 'Particulier'), ('2', 'Institution'), ('3', 'Commerçant'), ('4', 'Nourriture sur place'), ('5', 'Entreprise de services'), ('6', 'Conférence'), ('7', 'Atelier'), ('7', 'autre')], default='0', max_length=10, verbose_name='Type de la structure'),
        ),
    ]
