# Generated by Django 2.2.27 on 2022-03-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permaculturelne', '0014_auto_20200213_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscriptionbenevole',
            name='jour_dim',
        ),
        migrations.RemoveField(
            model_name='inscriptionbenevole',
            name='jour_lun',
        ),
        migrations.RemoveField(
            model_name='inscriptionexposant',
            name='jours_festival',
        ),
        migrations.RemoveField(
            model_name='inscriptionexposant',
            name='plaque',
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jour_jeu',
            field=models.BooleanField(default=False, verbose_name='Disponible le Jeudi 13 octobre'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jour_mer',
            field=models.BooleanField(default=False, verbose_name='Disponible le Mercredi 12 octobre'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jour_sam',
            field=models.BooleanField(default=False, verbose_name='Disponible le Samedi 15 octobre'),
        ),
        migrations.AlterField(
            model_name='inscriptionbenevole',
            name='jour_ven',
            field=models.BooleanField(default=False, verbose_name='Disponible le Vendredi 14 octobre'),
        ),
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='statut_exposant',
            field=models.CharField(choices=[('0', 'Inscription déposée'), ('1', 'Inscription incomplète ou en cours de validation'), ('5', 'Inscription valide mais en attente du cheque de caution'), ('2', 'Inscription validée'), ('3', 'Inscription refusée'), ('4', 'Inscription annulée')], default='0', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='type_exposant',
            field=models.CharField(choices=[('0', 'Association'), ('1', 'Particulier'), ('2', 'Institution'), ('3', 'Commerçant'), ('4', 'Restauration'), ('5', 'Entreprise de services'), ('6', 'Conférence'), ('7', 'Atelier'), ('8', 'autre')], default='0', max_length=10, verbose_name='Type de la structure'),
        ),
    ]
