# Generated by Django 2.2.27 on 2022-04-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permaculturelne', '0015_auto_20220320_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscriptionexposant',
            name='domaine_exposant',
        ),
        migrations.RemoveField(
            model_name='inscriptionexposant',
            name='is_tombola',
        ),
        migrations.RemoveField(
            model_name='inscriptionexposant',
            name='lot_tombola',
        ),
        migrations.RemoveField(
            model_name='inscriptionexposant',
            name='type_exposant',
        ),
        migrations.AddField(
            model_name='inscriptionexposant',
            name='nombre_chaises',
            field=models.CharField(choices=[(0, '----------'), ('1', '1 chaise'), ('2', '2 chaises'), ('3', '3 tables'), ('4', '5 chaises'), ('5', '5 chaises')], default='0', max_length=2, verbose_name='Combien de chaises voulez vous réserver ?'),
        ),
        migrations.AddField(
            model_name='inscriptionexposant',
            name='nombre_grilles',
            field=models.CharField(choices=[(0, '----------'), ('1', 'pas de grille'), ('2', '2 grilles'), ('3', '4 grilles')], default='0', max_length=2, verbose_name='Combien de grilles voulez vous réserver (par paire) ?'),
        ),
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='nombre_tables',
            field=models.CharField(choices=[(0, '----------'), ('1', 'pas de table'), ('2', '1 table'), ('3', '2 tables')], default='0', max_length=2, verbose_name='Combien de tables voulez vous réserver ?'),
        ),
    ]
